name: NYTimes Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Roda a cada hora
  workflow_dispatch:  # Permite execução manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests

      - name: Criar arquivo de API Key
        run: echo "API_KEY=${{ secrets.API_KEY }}" > .env

      - name: Executar script
        run: python nyt.py

      - name: Commit dos dados coletados
        run: |
          git config --global user.name "St3vs"
          git config --global user.email "rodrigoesteves30@gmail.com"
          git add dados.json
          git commit -m "Atualização automática de artigos do NYTimes" || echo "Nada para commitar"
          git push
