name: NYTimes Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Roda a cada hora
  workflow_dispatch:  # Permite execução manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Permite o GitHub Actions realizar push de conteúdo
      pull-requests: write  # Se for necessário para abrir pull requests

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests

      - name: Criar arquivo de API Key
        run: echo "API_KEY=${{ secrets.API_KEY }}" > .env

      - name: Executar script
        run: python nyt.py

      - name: Commit dos dados coletados
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add dados.json  ficheiro.log
          git commit -m "Atualização automática de artigos do NYTimes" || echo "Nada para commitar"
          git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/St3vs/nytimesapi.git
